name: NAMEREQUEST UI CD

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        options:
          - dev
          - test
          - sandbox
          - prod

jobs:
  namerequest-ui-cd:
    uses: bcgov/bcregistry-sre/.github/workflows/frontend-cd.yaml@main
    with:
      target: ${{ inputs.environment }}
      node_version: '20.5.1'
      app_name: 'namerequest'
      working_directory: 'app'
    secrets:
      WORKLOAD_IDENTIFY_POOLS_PROVIDER: ${{ secrets.WORKLOAD_IDENTIFY_POOLS_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

